version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./pg.dockerfile
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_USER: user
      POSTGRES_DB: HomeAuto
    ports:
      - '5438:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    
    networks:
      - local

  goapp:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./:/app

    networks:
      - local

  
networks:
  local:
    driver: bridge