version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./pg.dockerfile
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_USER: user
      POSTGRES_DB: HomeAuto
    ports:
      - '5438:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    
    networks:
      - local

  goapp:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./:/app

    networks:
      - local

  frontend:
    build:
      context: ./frontend/
    restart: always
    ports:
      - 5001:5000 
    volumes: 
      - ./frontend/src/:/usr/app/src
    networks:
      - local

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - goapp
      - frontend
    ports:
      - 8000:8000
    volumes:
      - ./nginx:/etc/nginx
      #network_mode: host
    networks:
      - local

  
networks:
  local:
    driver: bridge
